@tanstack/react-router
@/components/site-nav
@/components/site-footer
@/components/whatsapp-float
@/assets/williane-hero.jpg
@/assets/williane-sobre-nova.jpg
@/assets/tipo-tradicional.jpg
@/assets/tipo-gourmet.jpg
@/assets/tipo-tematico.jpg
@/assets/portfolio-1.jpeg
@/assets/portfolio-2.jpeg
@/assets/portfolio-3.jpeg
@/assets/portfolio-4.jpeg
@/assets/portfolio-5.jpeg
@/assets/portfolio.jpeg
